### PR TITLE
Fix CSS class typo regarding naming convention

### LINKED ISSUE #167: typo in CSS classes naming
Refering to this document : https://github.com/ckeditor/ckeditor5-design/wiki/Code-Style-Naming-Guidelines

There is a typo in those classes :  
https://github.com/ckeditor/ckeditor5-image/blob/master/theme/textalternativeform.css

I expect this selector `[class^='ck-']` to match every CKEditor UI.

### LINKED ISSUE #5131: typo in CSS classes naming
Refering to this document : https://github.com/ckeditor/ckeditor5-design/wiki/Code-Style-Naming-Guidelines

There is a typo in those classes :  
https://github.com/ckeditor/ckeditor5-image/blob/master/theme/textalternativeform.css

I expect this selector `[class^='ck-']` to match every CKEditor UI.

### PR DESCRIPTION
**Pull request by long-lazuli**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Type: Message. Closes ckeditor/ckeditor5#5131 .

### CODE REVIEW

**Comment by pomek** [comment]
@szymonkups noticed that Travis build for this PR does not work. I found [this in Travis docs](https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions):

> Pull requests sent from forked repositories do not have access to encrypted variables or data.

What should we do in such situation? 

cc: @Reinmar

**Comment by pomek** [comment]
image

**Comment by Reinmar** [comment]
We'll need to fix it, @pomek, as you reported yourself :D https://github.com/ckeditor/ckeditor5-dev/issues/358

**Comment by long-lazuli** [comment]
Is there something I can do ?
No one works on a forked repo, in your team ?

**Comment by Reinmar** [comment]
> Is there something I can do ?

https://github.com/ckeditor/ckeditor5-dev/issues/358 seems to be rather cosmetic change, so it's just a matter of doing and verifying it. I think we're fine here, thanks :)

> No one works on a forked repo, in your team ?

No – we work on the original repositories. Working on forks would add a lot of overhead to our workflow (which isn't that simple due to the multi-repo architecture anyway).

**Comment by oleq** [comment]
This fix has already been included as a part of a [PR](https://github.com/ckeditor/ckeditor5-image/pull/172/files) with the refreshed Lark theme. It changes the structure of the UI anyway.

**Comment by oleq** [comment]
More info in https://github.com/ckeditor/ckeditor5-ui/issues/112.

**Pull request closed without merging**
