### PR TITLE
T/ckeditor5/1985: Change how the temporary upload image is handled.

### LINKED ISSUE #1985: Can't add an image to a table
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

Latest

## 📋 Steps to reproduce
Try to add an image to an existing table. The image isn't displayed and only image caption appears.

## ✅ Expected result

Image added to the table

## ❎ Actual result

The image is not added to the table. Various errors in the console.

## 📃 Other details that might be useful

 Console shows errors like:
```
TypeError: undefined is not an object (evaluating 'entry[ 0 ]')
```
```
TypeError: this._visibleStack is undefined
TypeError: entry is undefined
```

Screenshot 2019-08-21 at 11 25 42

### PR DESCRIPTION
**Pull request by jodator**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Image upload should handle images that are deeply nested in other blocks. Closes ckeditor/ckeditor5#1985.

---

### Additional information

* Rendering of the temporary image is done in a downcast conversion instead of listening on the `doc.change` event.
* Requires changes in:
    - upload plugin: https://github.com/ckeditor/ckeditor5-upload/pull/99.
    - table plugin: https://github.com/ckeditor/ckeditor5-table/pull/212

### CODE REVIEW

**Comment by Reinmar** [comment]
Unfortunately, it does not work still:

image

**Comment by Reinmar** [comment]
Error:

image

**Comment by jodator** [comment]
Above mentioned bugs fixed with: https://github.com/ckeditor/ckeditor5-table/pull/212. Anyway, we will need a follow-up with better upload checking so the upload (and cleanup) is not triggered more than once for the same image.

**Comment by Mgsy** [comment]
Now everything works fine 👌

**Pull request merged**
